### ISSUE TITLE
FileNotFoundError (unable to download course probabilistic-graphical-models)

### ISSUE THREAD

**Issue by Huang-Chuan** [feng-lei/dl_coursera#14]
I can download other course from coursera using command like following:
`dl_coursera --cookies /E/cookies-coursera-org.txt --slug probabilistic-graphical-models --outdir probabilistic-graphical-models --how aria2-rpc`

However, when I tried to download **probabilistic-graphical-models**, I got following error. 

2020-04-21 13:24:35,519 - MainThread - new directory tree: F:\Tutorials\unsorted coursera-dl\probabilistic-graphical-models\probabilistic-graphical-models\resource
2020-04-21 13:24:35,520 - MainThread - new file: F:\Tutorials\unsorted coursera-dl\probabilistic-graphical-models\probabilistic-graphical-models\references\01@textbook.html
2020-04-21 13:24:35,522 - MainThread - new file: F:\Tutorials\unsorted coursera-dl\probabilistic-graphical-models\probabilistic-graphical-models\references\02@course-staff.html
Traceback (most recent call last):
  File "c:\users\chuanhuang\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chuanhuang\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ChuanHuang\AppData\Local\Programs\Python\Python36\Scripts\dl_coursera.exe\__main__.py", line 9, in <module>
  File "c:\users\chuanhuang\appdata\local\programs\python\python36\lib\site-packages\dl_coursera_run.py", line 180, in main
    dl_tasks = gather_dl_tasks(args['outdir'], soc)
  File "c:\users\chuanhuang\appdata\local\programs\python\python36\lib\site-packages\dl_coursera_run.py", line 89, in gather_dl_tasks
    dl_tasks = DLTaskGatherer(soc=soc, outdir=outdir).gather()
  File "c:\users\chuanhuang\appdata\local\programs\python\python36\lib\site-packages\dl_coursera\DLTaskGatherer.py", line 48, in gather
    with open(filename, 'wb') as ofs:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Tutorials\\unsorted coursera-dl\\probabilistic-graphical-models\\probabilistic-graphical-models\\02@bayesian-network-directed-models\\04@octave-installation-and-tutorial-from-pr\\01@setting-up-your-programming-assignment-e\\01@setting-up-your-programming-assignment-e.html
`

**Comment by feng-lei** [comment]
You need to disable the Windows path length limit of 260 characters, and google will help you find the instructions for your Windows version.

**Comment by Huang-Chuan** [comment]
@feng-lei   Great! It works. Thank you!
