### ISSUE TITLE
dl_coursera.define.CookiesExpiredException: The cookies.txt expired

### ISSUE THREAD

**Issue by zenny** [feng-lei/dl_coursera#16]
Hi,

I have an issue with the latest cookies.txt from the browser:

```
$ dl_coursera --cookies ~/Downloads/coursera_cookies.txt --slug <COURSE ID> --outdir <path/to/output/dir> --how curl
Traceback (most recent call last):
  File "/home/zenny/.local/bin/dl_coursera", line 8, in <module>
    sys.exit(main())
  File "/home/zenny/.local/lib/python3.8/site-packages/dl_coursera_run.py", line 178, in main
    soc = crawl(args['cookies'], args['slug'], args['isSpec'], args['outdir'], args['n_worker'])
  File "/home/zenny/.local/lib/python3.8/site-packages/dl_coursera_run.py", line 65, in crawl
    raise CookiesExpiredException()
```

Tried with builtin, aria2 and curl, but getting the same results. Any clue?

Cheers,
/z

**Comment by feng-lei** [comment]
You need to update the `cookies.txt`, refer to [README.md](https://github.com/feng-lei/dl_coursera/blob/master/README.md) for intructions.

**Comment by merberich** [comment]
Also make sure you are using the "coursera.org" cookies and **not** the "www.coursera.org" cookies (there is a difference).

**Comment by DeepsiA** [comment]
Hi @merberich , I am generating a new cookies.txt file using the chrome extension, and right away trying to download the files but I am still getting the exception `CookiesExpiredException()`.

Also, how do we use only `coursera.org`; browser is redirecting me to `https://www.coursera.org`

Below is the command, I am using
`>dl_coursera --cookies F:/Downloads/cookies.txt --slug machine-learning --how builtin --outdir path`

**Comment by FLZ101** [comment]
Have you checked content of the `cookies.txt` to make sure it is the `cookies.txt` of [Coursera](www.coursera.org) ?

**Comment by DeepsiA** [comment]
> Have you checked content of the `cookies.txt` to make sure it is the `cookies.txt` of [Coursera](www.coursera.org) ? @DeepsiA

@FLZ101 
Below attached is the content of my generated `cookies.txt` file.
```
# HTTP Cookie File downloaded with cookies.txt by Genuinous @genuinous
# This file can be used by wget, curl, aria2c and other standard compliant tools.
# Usage Examples:
#   1) wget -x --load-cookies cookies.txt "https://www.coursera.org/"
#   2) curl --cookie cookies.txt "https://www.coursera.org/"
#   3) aria2c --load-cookies cookies.txt "https://www.coursera.org/"
#
.www.coursera.org	TRUE	/	TRUE	0	G_AUTHUSER_H	0
```

Steps followed - 
1. Launched www.coursera.org
2. Click on extension -> cookies.txt -> `Download Here`

**Comment by FLZ101** [comment]
Had you signed in before getting the `cookies.txt`? @DeepsiA

**Comment by DeepsiA** [comment]
@FLZ101  Yes. I am logged in with my Coursera Account.

**Comment by FLZ101** [comment]
The `cookies.txt` I got just now looks quite different from the one you got. @DeepsiA 

```
# HTTP Cookie File downloaded with cookies.txt by Genuinous @genuinous
# This file can be used by wget, curl, aria2c and other standard compliant tools.
# Usage Examples:
#   1) wget -x --load-cookies cookies.txt "https://www.coursera.org/"
#   2) curl --cookie cookies.txt "https://www.coursera.org/"
#   3) aria2c --load-cookies cookies.txt "https://www.coursera.org/"
#
.coursera.org	TRUE	/	FALSE	1603610152	__204u	9013717...
.coursera.org	TRUE	/	FALSE	1603894717	__204r	htt...
.coursera.org	TRUE	/	FALSE	1664283449	_ga	GA1.2.66...
.coursera.org	TRUE	/	FALSE	1604471417	_hjid	56ee...
...
```

**Comment by DeepsiA** [comment]
Did you follow the same steps as I mentioned @FLZ101  or am I doing something wrong in generating the cookies?

**Comment by FLZ101** [comment]
I followed the same steps described in [README](https://github.com/FLZ101/dl_coursera/blob/master/README.md), just as you did.

**Comment by utpal150894** [comment]
first try to login in your browser ...let it open in a tab ....then try to fetch the cookies text....it will work..

**Comment by RedemptionC** [comment]
make sure you are exporting cookies of coursera.com not www.coursera.com
I am using firefox,its extension will ask you this
