### ISSUE TITLE
JSONDecoderERROR

### ISSUE THREAD

**Issue by liwentao-123** [feng-lei/dl_coursera#17]
Hello,author:
I have meet a error as follows:
"""
dl_coursera --cookies E:\coursera\cookies-www-coursera-org.txt --slug deep-neural-networks-with-pytorch --outdir E:\Pytorch --how builtin
Traceback (most recent call last):
  File "d:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\dl_coursera.exe\__main__.py", line 7, in <module>
  File "d:\programdata\anaconda3\lib\site-packages\dl_coursera_run.py", line 178, in main
    soc = crawl(args['cookies'], args['slug'], args['isSpec'], args['outdir'], args['n_worker'])
  File "d:\programdata\anaconda3\lib\site-packages\dl_coursera_run.py", line 54, in crawl
    if 'elements' not in sess.get(URL_COURSE_1(slug)).json():
  File "d:\programdata\anaconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "d:\programdata\anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "d:\programdata\anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\programdata\anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

  So,how to deal with this problem ?If you have seen it ,reply to me please.
  Thanks you!

**Comment by feng-lei** [comment]
The error occurred very early even before crawling started. The `cookies.txt` might not be right, try getting a new one. Refer to [README.md](https://github.com/feng-lei/dl_coursera/blob/master/README.md) for instructions.
