### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by JasmineYJ** [feng-lei/dl_coursera#18]
I've downloaded other classes with no issue, except the following :
------------------------------------------------------
2020-05-17 13:43:59,120 - 3 - [Done] priority=C, ttl=3. crawl_lecture: course=mcit595-spring2020, lecture=spring-2020-jan-28-open-office-hour-recording
Traceback (most recent call last):
  File "/opt/anaconda3/bin/dl_coursera", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/dl_coursera_run.py", line 178, in main
    soc = crawl(args['cookies'], args['slug'], args['isSpec'], args['outdir'], args['n_worker'])
  File "/opt/anaconda3/lib/python3.7/site-packages/dl_coursera_run.py", line 71, in crawl
    soc = crawler.crawl(slug=slug, isSpec=isSpec)
  File "/opt/anaconda3/lib/python3.7/site-packages/dl_coursera/Crawler.py", line 313, in crawl
    assert len(failures) == 0
AssertionError

**Comment by feng-lei** [comment]
As a temporary solution, removing line 313 of `/opt/anaconda3/lib/python3.7/site-packages/dl_coursera/Crawler.py` should help.

**Comment by ulissesBR** [comment]
Had the same issue, feng-lei's workaround worked for me.

**Comment by IMINABO1** [comment]
I am also having the same error. The solution is not working. I have never encountered this error
`2022-11-26 23:12:58,877 - 3 - [Done] priority=C, ttl=3. crawl_lecture: course=decision-making, lecture=specialization-overview
Traceback (most recent call last):
  File "C:\Users\NIMASA\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NIMASA\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\NIMASA\AppData\Local\Programs\Python\Python310\Scripts\dl_coursera.exe\__main__.py", line 7, in <module>
  File "C:\Users\NIMASA\AppData\Local\Programs\Python\Python310\lib\site-packages\dl_coursera_run.py", line 178, in main
    soc = crawl(args['cookies'], args['slug'], args['isSpec'], args['outdir'], args['n_worker'])
  File "C:\Users\NIMASA\AppData\Local\Programs\Python\Python310\lib\site-packages\dl_coursera_run.py", line 71, in crawl
    soc = crawler.crawl(slug=slug, isSpec=isSpec)
  File "C:\Users\NIMASA\AppData\Local\Programs\Python\Python310\lib\site-packages\dl_coursera\Crawler.py", line 313, in crawl
    assert len(failures) == 0
AssertionError`
