### ISSUE TITLE
help me to solve

### ISSUE THREAD

**Issue by jaan143** [feng-lei/dl_coursera#2]
please help me to solve this issue i want to use your script
PS C:\Users\vicky\downloads> dl_coursera --cookies c:/Users/vicky/Downloads/cookies.txt --slug machine-learning --outdir
 c:/Users/vicky/Downloads --how curl
usage: dl_coursera [-h] [--version] --email EMAIL --password PASSWORD --slug
                   SLUG [--isSpec] [--n-worker N_WORKER] [--outdir OUTDIR]
                   --how {builtin,curl,aria2,aria2-rpc,uget}
                   [--generate-input-file] [--aria2-rpc-url ARIA2_RPC_URL]
                   [--aria2-rpc-secret ARIA2_RPC_SECRET]
dl_coursera: error: the following arguments are required: --email, --password
PS C:\Users\vicky\downloads>

**Comment by feng-lei** [comment]
Make sure you are using the latest version (`dl_coursera 0.1.1`). You can upgrade `dl_coursera` via  `pip install -U dl_coursera`.

**Comment by jaan143** [comment]
i installed latest version and please tell me did my command is right or wrong

**Comment by feng-lei** [comment]
It seems that you are not using the latest version (0.1.1).

```
$ dl_coursera --version
dl_coursera 0.1.1
```

**Comment by jaan143** [comment]
i updated and now its downloading reading files only not video lectures
this is command i am using
dl_coursera --cookies c:/Users/vicky/Downloads/cookies.txt --slug machine-learning-with-python --outdir c:/Users/vicky/Downloads --how curl

2019-09-07 18:45:40,565 - 3 - [Failed] priority=A, ttl=3. download: url=https://www.coursera.org/api/subtitleAssetProxy.v1/GvUsfoRSEeiEShL6YrwsWg?expiry=1567987200000&hmac=aa13XIPhRpnChloC604IKtF83zhTG9FaR0ZndnlNqoU&fileExtension=srt, filename=c:\Users\vicky\Downloads\machine-learning-with-python\01@introduction-to-machine-learning\01@what-is-machine-leaning\02@introduction-to-machine-learning\01@.srt
Traceback (most recent call last):
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\site-packages\dl_coursera\lib\TaskScheduler.py", line 167, in _func_work
    task.run()
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\site-packages\dl_coursera\lib\TaskScheduler.py", line 44, in run
    self.go()
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\site-packages\dl_coursera\lib\TaskScheduler.py", line 75, in go
    self._func(**self._kwargs)
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\site-packages\dl_coursera\Downloader.py", line 58, in _dl
    stderr=subprocess.STDOUT, check=True)
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\users\vicky\appdata\local\programs\python\python36-32\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by feng-lei** [comment]
It seems that curl is not installed.

You need to install [curl](https://curl.haxx.se/windows/) first.

```
$ curl --version
curl 7.62.0 (x86_64-pc-win32) libcurl/7.62.0 OpenSSL/1.1.1a (WinSSL) zlib/1.2.11 brotli/1.0.7 WinIDN libssh2/1.8.0 nghttp2/1.35.0
Release-Date: 2018-10-31
```

**Comment by feng-lei** [comment]
Or you can just use the builtin downloader instead of curl.

```
$ dl_coursera --cookies c:/Users/vicky/Downloads/cookies.txt --slug machine-learning --outdir
c:/Users/vicky/Downloads --how builtin
```

**Comment by jaan143** [comment]
this option is working fine 
actually i downloaded curl and then i created a folder call "curl" in c drive after that i put that folder path in veriable environment setting but i dont know how to install curl application

**Comment by feng-lei** [comment]
Does the file `C:/curl/bin/curl.exe` exist? Then prepend the directory `C:/curl/bin` to the PATH.

```
$ set PATH=C:\curl\bin;%PATH%
$ curl --version
```

**Comment by jaan143** [comment]
@feng-lei 
i need python project and i will pay you for it
give me your email i will send you details

**Comment by feng-lei** [comment]
fenglei4518@hotmail.com

**Comment by jaan143** [comment]
@feng-lei  i am sorry i cant see your reply
i sent you details in email please check and reply me in email

thank you
